"""change table shop_license

Revision ID: 3d8f3b58b3af
Revises: 8f114cd869c7
Create Date: 2018-12-24 17:22:52.180315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d8f3b58b3af'
down_revision = '8f114cd869c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop_info', 'shop_img_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('shop_items', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.add_column('shop_license', sa.Column('business_image_name', sa.String(length=100), nullable=True))
    op.add_column('shop_license', sa.Column('idcard_image_name', sa.String(length=100), nullable=True))
    op.add_column('shop_license', sa.Column('service_image_name', sa.String(length=100), nullable=True))
    op.drop_column('shop_license', 'business_img')
    op.drop_column('shop_license', 'service_img')
    op.drop_column('shop_license', 'idcard_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_license', sa.Column('idcard_img', sa.BLOB(), nullable=True))
    op.add_column('shop_license', sa.Column('service_img', sa.BLOB(), nullable=True))
    op.add_column('shop_license', sa.Column('business_img', sa.BLOB(), nullable=True))
    op.drop_column('shop_license', 'service_image_name')
    op.drop_column('shop_license', 'idcard_image_name')
    op.drop_column('shop_license', 'business_image_name')
    op.alter_column('shop_items', 'status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('shop_info', 'shop_img_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('role', 'default',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
