"""empty message

Revision ID: 7ca983baab18
Revises: a209625c85ea
Create Date: 2018-12-16 16:33:37.308394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca983baab18'
down_revision = 'a209625c85ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_region_parent_id'), 'region', ['parent_id'], unique=False)
    op.create_index(op.f('ix_region_region_id'), 'region', ['region_id'], unique=False)
    op.create_index(op.f('ix_region_region_type'), 'region', ['region_type'], unique=False)
    op.add_column('shop_info', sa.Column('shop_img_name', sa.String(length=50), nullable=True))
    op.drop_column('shop_info', 'shop_img_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_info', sa.Column('shop_img_id', sa.BLOB(), nullable=True))
    op.drop_column('shop_info', 'shop_img_name')
    op.drop_index(op.f('ix_region_region_type'), table_name='region')
    op.drop_index(op.f('ix_region_region_id'), table_name='region')
    op.drop_index(op.f('ix_region_parent_id'), table_name='region')
    # ### end Alembic commands ###
