"""添加了后台的

Revision ID: 90c068e2a800
Revises: 3d8f3b58b3af
Create Date: 2018-12-24 23:09:50.995713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90c068e2a800'
down_revision = '3d8f3b58b3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('head_img', sa.LargeBinary(length=2048), nullable=True))
    op.alter_column('admin', 'admin_phone',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=11),
               existing_nullable=True)
    op.drop_constraint('admin_ibfk_1', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'role', ['role_id'], ['id'])
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop_items', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('shop_license', 'business_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shop_license', 'business_end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('shop_license', 'business_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('shop_license', 'business_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
    op.alter_column('shop_license', 'idcard_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('shop_license', 'idcard_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
    op.alter_column('shop_license', 'service_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shop_license', 'service_begin_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('shop_license', 'service_end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('shop_license', 'service_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('shop_license', 'service_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
    op.alter_column('shop_license', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_license', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('shop_license', 'service_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
    op.alter_column('shop_license', 'service_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('shop_license', 'service_end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('shop_license', 'service_begin_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('shop_license', 'service_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shop_license', 'idcard_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
    op.alter_column('shop_license', 'idcard_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('shop_license', 'business_num',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
    op.alter_column('shop_license', 'business_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('shop_license', 'business_end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('shop_license', 'business_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shop_items', 'status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('role', 'default',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_ibfk_1', 'admin', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('admin', 'admin_phone',
               existing_type=sa.String(length=11),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('admin', 'head_img')
    # ### end Alembic commands ###
