"""state --> status

Revision ID: 99d462daf5c8
Revises: 24898aef5f62
Create Date: 2018-12-23 14:27:27.037819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99d462daf5c8'
down_revision = '24898aef5f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_back_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personal_reason', sa.String(length=300), nullable=False),
    sa.Column('shop_reason', sa.String(length=300), nullable=True),
    sa.Column('admin_reason', sa.String(length=300), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('orders', 'state')
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('shop_info', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('shop_info', 'state')
    op.add_column('shop_items', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('shop_items', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('shop_items', 'status')
    op.add_column('shop_info', sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('shop_info', 'status')
    op.alter_column('role', 'default',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('orders', sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('orders', 'status')
    op.drop_table('charge_back_info')
    # ### end Alembic commands ###
