"""empty message

Revision ID: b1e33c9d5a20
Revises: a5c5f1dbe945
Create Date: 2018-12-09 16:13:18.890051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1e33c9d5a20'
down_revision = 'a5c5f1dbe945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shop', sa.Column('nickname', sa.String(length=64), nullable=False))
    op.drop_column('user_shop', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shop', sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('user_shop', 'nickname')
    # ### end Alembic commands ###
