"""empty message

Revision ID: bcbe9eb87361
Revises: 7ca983baab18
Create Date: 2018-12-17 09:04:26.543795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcbe9eb87361'
down_revision = '7ca983baab18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_name', sa.String(length=20), nullable=False))
    op.alter_column('order_items', 'item_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_items', 'item_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop_items', 'state',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_items', 'state',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('role', 'default',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_items', 'item_price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('order_items', 'item_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('order_items', 'item_name')
    # ### end Alembic commands ###
