"""empty message

Revision ID: ee11ecd82780
Revises: 3f55b2d6e947
Create Date: 2018-11-25 23:23:16.836970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee11ecd82780'
down_revision = '3f55b2d6e947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_personal', 'head_img',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('user_personal', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_personal', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user_personal', 'head_img',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###
