"""update orders

Revision ID: f8b2ba73b230
Revises: e861b31f7b52
Create Date: 2018-12-18 16:24:02.600641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8b2ba73b230'
down_revision = 'e861b31f7b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_str', sa.String(length=200), nullable=False))
    op.add_column('orders', sa.Column('contact_phone', sa.String(length=11), nullable=False))
    op.add_column('orders', sa.Column('receiver', sa.String(length=20), nullable=False))
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('shop_items', 'state',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_items', 'state',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('role', 'default',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('orders', 'receiver')
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'address_str')
    # ### end Alembic commands ###
